### ISSUE TITLE
能提供javascript版本的分词吗？

### ISSUE THREAD

**Issue by tiandaox** [leizongmin/node-segment#15]
因为不懂node.js语法，从node.js变成js有一点困难。

**Comment by leizongmin** [comment]
这个模块本身是纯js写的，理论上可以在任何支持ECMAScript 5的环境下运行。但因为需要载入一个较大的词库，并且允许过程中需要占用较大的内存，在浏览器环境下运行似乎不太好，而且也很少会有人在浏览器环境下使用它。

**Comment by leizongmin** [comment]
@rekey 可以利用此模块自行搭建分词服务
