### ISSUE TITLE
这句话解析不了

### ISSUE THREAD

**Issue by JimLiu** [leizongmin/node-segment#16]
尝试解析这句，结果无响应：
`无耻啊无耻，西工大图书馆  标题要长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长`

**Comment by vczero** [comment]
果真分词不了啊。目前还不敢用于实际产品啊

**Comment by jebai0521** [comment]
这取决于词库的大小，现在词库有限

**Comment by leizongmin** [comment]
README中有说明 **请勿用此模块来对较长且无任何标点符号的文本进行分词，否则会导致分词时间成倍增加。**

原因是分词时有深度探测各分支，如果分之深度太大会出现无响应情况

**Comment by houyhea** [comment]
既然有如此限制，是否可以考虑再分词前增加一个处理步骤：对于较长且无任何标点符号的文本，以及连续n个（n>5?)同样文字,单独处理，比如：主动增加分隔符来区分？

**Comment by newebug** [comment]
好奇用 https://github.com/newebug/node-analyzer 试了一下，无压力：
result:  无耻 啊 无耻 ， 西工大 图书馆   标题 要 长长 长长 长长 长长 长长 长长 长长 长长 长长 长长 长长 长长 长长 长长 长长 长长 长

也是基于字典的 ik-analyzer 的实现，作者不好意思了，有拉用户的嫌疑

**Comment by leizongmin** [comment]
@newebug 优秀的东西就应该让更多人知道，无所谓「拉用户的嫌疑」
