### ISSUE TITLE
请勿用此模块来对较长且无任何标点符号的文本进行分词，否则会导致分词时间成倍增加

### ISSUE THREAD

**Issue by 820465323** [leizongmin/node-segment#36]
导致分词时间成倍增加的原因是什么呢？ 没看到大佬有说明呀
因为我们前几天在使用nodejieba发现了环境兼容性问题，决定放弃它采用node-segment，但是想知道它的稳定性和分词时间倍增的原因
@leizongmin

**Comment by leizongmin** [comment]
主要是分词算法实现问题，如果句子太长没有断句（标点符号可以断句）会导致程序探索 M^N 种可能，最终可能内存会爆掉。
这个项目已经不再维护了，建议还是用 jieba 好一点。

**Comment by 820465323** [comment]
查了很多资料 没有找到nodejs维护的比较好的中文分词。
nodejieba对环境的要求比较苛刻，在部署的时候遇到了gcc版本过低的问题，但是我们无法更换gcc版本，因为可能会影响到其他服务。
所以还是考虑使用您的这个分词包，看了下都是js写的，所以对环境兼容性是没的说。
我们平均每次分词不会超过100个字符，那么应该不会遇到您说的内存问题吧

**Comment by leizongmin** [comment]
只有试过才知道咯。
